### ISSUE TITLE
Could you please share the combine_hic function?

### ISSUE THREAD

**Issue by Xuyuch** [Xieeeee/Droplet-Hi-C#1]
Dear Yang,
    Thank you for providing your analysis to do the Droplet-HiC methods. We found it would be useful in our research study and we want to make the code run in our local work station. However, there are some your homemade code which is not viewable to the public. For example: The code in your  _04.proc_paired_hic_v2.1.sh_ used lines of code as below:
```
    echo "process scHiC fastq... mode: "${mode}
/projects/ps-renlab/y2xie/packages/Paired-Tag-master/reachtools/reachtools combine_hic ${mode} ${fastq_dir}/${s}
(zcat ${fastq_dir}/${s}_R1_combined.fq.gz | bowtie -x ${ref_10X} - --nofw -m 1 -v 1 -S ${fastq_dir}/${s}_R1_BC.sam) 2>${fastq_dir}/${s}_R1.log
zcat ${fastq_dir}/${s}_R3_combined.fq.gz | bowtie -x ${ref_10X} - --nofw -m 1 -v 1 -S ${fastq_dir}/${s}_R3_BC.sam

/projects/ps-renlab/y2xie/packages/Paired-Tag-master/reachtools/reachtools convert_hic2 ${fastq_dir}/${s}_R1_BC.sam
/projects/ps-renlab/y2xie/packages/Paired-Tag-master/reachtools/reachtools convert_hic2 ${fastq_dir}/${s}_R3_BC.sam
```
I search in _Paired-Tag package_ and the latest version does not have _combine_hic_ and _convert_hic2_  function.

I guess this function is used for single cell barcode and UMI retrieving from the hic data, I would really appreciate if you could provide a small descripton about how to use those functions and what they are doing. Thank you.

Also, In the SRR database, I didn't see the Read 3. Do you have a special R3 for those HiC reads? Please let me know. 

Thanks,
Yuchen

**Comment by Xieeeee** [comment]
Hi Xuyuch,
Thanks for your interest in Droplet Hi-C! Your guess are correct. `combine_hic` and `convert_hic2` serves to extract and parse the 10X barcodes into readname, so that it can be kept during alignment and extracted during `pairtools parse`. I have uploaded them to https://github.com/Xieeeee/Droplet-Hi-C/tree/main/01.pre-process/scripts/hictools, you might need to modify the `04.proc_paired_hic_v2.1.sh` accordingly.

For the fastq files, I have reminded GEO to get the data released since I find most of my uploaded fastq being absent in the release version. But for your question, the index read (read with cell barcode) is treated as Read2 during 10X demultiplexing process, so the reverse read with genomic information (which should be "Read2" before) is the Read3. Hope this helps.

Best,
Yang

**Comment by Xuyuch** [comment]
Thanks for your reply. And I can see the codes now and I will try use the code works on the data.

As for the Read3 issue, I double checked the SRA database just now and found they uploaded the technique reads(barcode) recently(It was not there when I first download it). I am downloading the new reads now. Thanks for your valuable information.

Just to make sure, for Paired HiC you used barcode 'arc' kit and for normal Droplet HiC you used barcode from 'atac' kit, right?

Thanks again for your rapidly reply!

Best,
Yuchen

**Comment by Xieeeee** [comment]
Sounds good! Yes, the mode arc is to handle the Paired Hi-C data based on 10X Multiome kit.

**Comment by Xuyuch** [comment]
Perfect! Thank you!
